/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/components/ErrorView`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingView`; params?: Router.UnknownInputParams; } | { pathname: `/components/PostCard`; params?: Router.UnknownInputParams; } | { pathname: `/types/wordpress`; params?: Router.UnknownInputParams; } | { pathname: `/utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ErrorView`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LoadingView`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PostCard`; params?: Router.UnknownOutputParams; } | { pathname: `/types/wordpress`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/api`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/categories${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/components/ErrorView${`?${string}` | `#${string}` | ''}` | `/components/LoadingView${`?${string}` | `#${string}` | ''}` | `/components/PostCard${`?${string}` | `#${string}` | ''}` | `/types/wordpress${`?${string}` | `#${string}` | ''}` | `/utils/api${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/components/ErrorView`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingView`; params?: Router.UnknownInputParams; } | { pathname: `/components/PostCard`; params?: Router.UnknownInputParams; } | { pathname: `/types/wordpress`; params?: Router.UnknownInputParams; } | { pathname: `/utils/api`; params?: Router.UnknownInputParams; } | `/+not-found` | `/category/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
